### ISSUE TITLE
 Unable to set the web application class loader property [clearReferencesStatic] to [false] as the property does not exist.

### ISSUE THREAD

**Issue by sinc59** [jonbrouse/docker-ice#1]
Hi Jonathan,
when i launch the docker-compose, it doesn't work (sorry, I'm very primary with java language).
Here, you can find the output:

$ /usr/local/bin/docker-compose -f docker-compose.yml up

Recreating dockerice_ice_1...
Recreating dockerice_nginx_1...
Attaching to dockerice_ice_1, dockerice_nginx_1
ice_1   | | Loading Grails 2.4.4
ice_1   | | Configuring classpath
ice_1   | Aug 11, 2015 3:20:18 PM java.util.prefs.FileSystemPreferences$1 run
ice_1   | INFO: Created user preferences directory.
ice_1   | | Configuring classpath.
ice_1   | | Environment set to development
ice_1   | | Environment set to development.
ice_1   | | Environment set to development..
ice_1   | | Environment set to development...
ice_1   | | Environment set to development....
ice_1   | | Environment set to development.....
ice_1   | | Packaging Grails application
ice_1   | | Installing zip tomcat-8.0.20.zip...
ice_1   | | Installing zip tomcat-8.0.20.zip....
ice_1   | | Installing zip tomcat-8.0.20.zip.....
ice_1   | | Installed plugin tomcat-8.0.20
ice_1   | | Installed plugin tomcat-8.0.20.
ice_1   | | Installed plugin tomcat-8.0.20..
ice_1   | | Installed plugin tomcat-8.0.20...
ice_1   | | Installed plugin tomcat-8.0.20....
ice_1   | | Installed plugin tomcat-8.0.20.....
ice_1   | | Compiling 10 source files
ice_1   | 
ice_1   | | Compiling 10 source files.
ice_1   | | Compiling 10 source files..
ice_1   | | Compiling 10 source files
ice_1   | 
ice_1   | | Compiling 10 source files.
ice_1   | | Compiling 10 source files..
ice_1   | | Compiling 10 source files...
ice_1   | | Compiling 10 source files....
ice_1   | | Compiling 10 source files.....
ice_1   | | Compiling 62 source files
ice_1   | Note: Some input files use or override a deprecated API.
ice_1   | Note: Recompile with -Xlint:deprecation for details.
ice_1   | Note: Some input files use unchecked or unsafe operations.
ice_1   | Note: Recompile with -Xlint:unchecked for details.
ice_1   | | Compiling 62 source files.
ice_1   | | Compiling 62 source files..
ice_1   | | Compiling 62 source files...
ice_1   | | Compiling 62 source files....
ice_1   | | Compiling 62 source files.....
ice_1   | | Running Grails application
ice_1   | 2015-08-11 15:20:33,636 [main] INFO  http11.Http11NioProtocol  - Initializing ProtocolHandler ["http-nio-8080"]
ice_1   | 2015-08-11 15:20:33,654 [main] INFO  net.NioSelectorPool  - Using a shared selector for servlet write/read
ice_1   | 2015-08-11 15:20:33,665 [main] INFO  core.StandardService  - Starting service Tomcat
ice_1   | 2015-08-11 15:20:33,665 [main] INFO  core.StandardEngine  - Starting Servlet Engine: Apache Tomcat/8.0.20
ice_1   | 2015-08-11 15:20:33,736 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStatic] to [false] as the property does not exist.
ice_1   | 2015-08-11 15:20:33,737 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopThreads] to [false] as the property does not exist.
ice_1   | 2015-08-11 15:20:33,738 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopTimerThreads] to [false] as the property does not exist.
ice_1   | 2015-08-11 15:20:33,738 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesHttpClientKeepAliveThread] to [true] as the property does not exist.
ice_1   | 2015-08-11 15:20:33,744 [localhost-startStop-1] INFO  startup.ContextConfig  - No global web.xml found
ice_1   | 2015-08-11 15:20:33,859 [localhost-startStop-1] INFO  [localhost].[/ice]  - No Spring WebApplicationInitializer types detected on classpath
ice_1   | 2015-08-11 15:20:33,877 [localhost-startStop-1] INFO  [localhost].[/ice]  - Initializing Spring root WebApplicationContext
ice_1   | 2015-08-11 15:20:37,735 [localhost-startStop-1] INFO  context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
ice_1   | 2015-08-11 15:20:37,759 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
ice_1   | 2015-08-11 15:20:38,191 [localhost-startStop-1] INFO  http.AmazonHttpClient  - Unable to execute HTTP request:  -aws-billing-ice.s3.amazonaws.com
ice_1   | Message:  -aws-billing-ice.s3.amazonaws.com
ice_1   |     Line | Method
ice_1   | ->>  901 | lookupAllHostAddr                in java.net.InetAddress$1
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
ice_1   | |   1295 | getAddressesFromNameService      in java.net.InetAddress
ice_1   | |   1248 | getAllByName0 . . . . . . . . .  in     ''
ice_1   | |   1164 | getAllByName                     in     ''
ice_1   | |   1098 | getAllByName . . . . . . . . . . in     ''
ice_1   | |     45 | resolve                          in org.apache.http.impl.conn.SystemDefaultDnsResolver
ice_1   | |    278 | resolveHostname . . . . . . . .  in org.apache.http.impl.conn.DefaultClientConnectionOperator
ice_1   | |    162 | openConnection                   in     ''
ice_1   | |    294 | open . . . . . . . . . . . . . . in org.apache.http.impl.conn.ManagedClientConnectionImpl
ice_1   | |    641 | tryConnect                       in org.apache.http.impl.client.DefaultRequestDirector
ice_1   | |    480 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    906 | execute                          in org.apache.http.impl.client.AbstractHttpClient
ice_1   | |    805 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    685 | executeOneRequest                in com.amazonaws.http.AmazonHttpClient
ice_1   | |    460 | executeHelper . . . . . . . . .  in     ''
ice_1   | |    295 | execute                          in     ''
ice_1   | |   3710 | invoke . . . . . . . . . . . . . in com.amazonaws.services.s3.AmazonS3Client
ice_1   | |   1146 | getObject                        in     ''
ice_1   | |   1018 | getObject . . . . . . . . . . .  in     ''
ice_1   | |    334 | download                         in com.netflix.ice.common.AwsUtils
ice_1   | |    329 | download . . . . . . . . . . . . in     ''
ice_1   | |    317 | downloadFileIfNotExist           in     ''
ice_1   | |    101 | init . . . . . . . . . . . . . . in com.netflix.ice.basic.BasicReservationService
ice_1   | |     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment . . . . .  in     ''
ice_1   | |    296 | executeForCurrentEnvironment     in     ''
ice_1   | |    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run                              in java.lang.Thread
ice_1   | 2015-08-11 15:20:38,219 [localhost-startStop-1] INFO  http.AmazonHttpClient  - Unable to execute HTTP request:  -aws-billing-ice.s3.amazonaws.com
ice_1   | Message:  -aws-billing-ice.s3.amazonaws.com
ice_1   |     Line | Method
ice_1   | ->> 1252 | getAllByName0                    in java.net.InetAddress
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
ice_1   | |   1164 | getAllByName                     in     ''
ice_1   | |   1098 | getAllByName . . . . . . . . . . in     ''
ice_1   | |     45 | resolve                          in org.apache.http.impl.conn.SystemDefaultDnsResolver
ice_1   | |    278 | resolveHostname . . . . . . . .  in org.apache.http.impl.conn.DefaultClientConnectionOperator
ice_1   | |    162 | openConnection                   in     ''
ice_1   | |    294 | open . . . . . . . . . . . . . . in org.apache.http.impl.conn.ManagedClientConnectionImpl
ice_1   | |    641 | tryConnect                       in org.apache.http.impl.client.DefaultRequestDirector
ice_1   | |    480 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    906 | execute                          in org.apache.http.impl.client.AbstractHttpClient
ice_1   | |    805 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    685 | executeOneRequest                in com.amazonaws.http.AmazonHttpClient
ice_1   | |    460 | executeHelper . . . . . . . . .  in     ''
ice_1   | |    295 | execute                          in     ''
ice_1   | |   3710 | invoke . . . . . . . . . . . . . in com.amazonaws.services.s3.AmazonS3Client
ice_1   | |   1146 | getObject                        in     ''
ice_1   | |   1018 | getObject . . . . . . . . . . .  in     ''
ice_1   | |    334 | download                         in com.netflix.ice.common.AwsUtils
ice_1   | |    329 | download . . . . . . . . . . . . in     ''
ice_1   | |    317 | downloadFileIfNotExist           in     ''
ice_1   | |    101 | init . . . . . . . . . . . . . . in com.netflix.ice.basic.BasicReservationService
ice_1   | |     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment . . . . .  in     ''
ice_1   | |    296 | executeForCurrentEnvironment     in     ''
ice_1   | |    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run                              in java.lang.Thread
ice_1   | 2015-08-11 15:20:38,825 [localhost-startStop-1] INFO  http.AmazonHttpClient  - Unable to execute HTTP request:  -aws-billing-ice.s3.amazonaws.com
ice_1   | Message:  -aws-billing-ice.s3.amazonaws.com
ice_1   |     Line | Method
ice_1   | ->> 1252 | getAllByName0                    in java.net.InetAddress
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
ice_1   | |   1164 | getAllByName                     in     ''
ice_1   | |   1098 | getAllByName . . . . . . . . . . in     ''
ice_1   | |     45 | resolve                          in org.apache.http.impl.conn.SystemDefaultDnsResolver
ice_1   | |    278 | resolveHostname . . . . . . . .  in org.apache.http.impl.conn.DefaultClientConnectionOperator
ice_1   | |    162 | openConnection                   in     ''
ice_1   | |    294 | open . . . . . . . . . . . . . . in org.apache.http.impl.conn.ManagedClientConnectionImpl
ice_1   | |    641 | tryConnect                       in org.apache.http.impl.client.DefaultRequestDirector
ice_1   | |    480 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    906 | execute                          in org.apache.http.impl.client.AbstractHttpClient
ice_1   | |    805 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    685 | executeOneRequest                in com.amazonaws.http.AmazonHttpClient
ice_1   | |    460 | executeHelper . . . . . . . . .  in     ''
ice_1   | |    295 | execute                          in     ''
ice_1   | |   3710 | invoke . . . . . . . . . . . . . in com.amazonaws.services.s3.AmazonS3Client
ice_1   | |   1146 | getObject                        in     ''
ice_1   | |   1018 | getObject . . . . . . . . . . .  in     ''
ice_1   | |    334 | download                         in com.netflix.ice.common.AwsUtils
ice_1   | |    329 | download . . . . . . . . . . . . in     ''
ice_1   | |    317 | downloadFileIfNotExist           in     ''
ice_1   | |    101 | init . . . . . . . . . . . . . . in com.netflix.ice.basic.BasicReservationService
ice_1   | |     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment . . . . .  in     ''
ice_1   | |    296 | executeForCurrentEnvironment     in     ''
ice_1   | |    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run                              in java.lang.Thread
ice_1   | 2015-08-11 15:20:40,035 [localhost-startStop-1] INFO  http.AmazonHttpClient  - Unable to execute HTTP request:  -aws-billing-ice.s3.amazonaws.com
ice_1   | Message:  -aws-billing-ice.s3.amazonaws.com
ice_1   |     Line | Method
ice_1   | ->> 1252 | getAllByName0                    in java.net.InetAddress
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
ice_1   | |   1164 | getAllByName                     in     ''
ice_1   | |   1098 | getAllByName . . . . . . . . . . in     ''
ice_1   | |     45 | resolve                          in org.apache.http.impl.conn.SystemDefaultDnsResolver
ice_1   | |    278 | resolveHostname . . . . . . . .  in org.apache.http.impl.conn.DefaultClientConnectionOperator
ice_1   | |    162 | openConnection                   in     ''
ice_1   | |    294 | open . . . . . . . . . . . . . . in org.apache.http.impl.conn.ManagedClientConnectionImpl
ice_1   | |    641 | tryConnect                       in org.apache.http.impl.client.DefaultRequestDirector
ice_1   | |    480 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    906 | execute                          in org.apache.http.impl.client.AbstractHttpClient
ice_1   | |    805 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    685 | executeOneRequest                in com.amazonaws.http.AmazonHttpClient
ice_1   | |    460 | executeHelper . . . . . . . . .  in     ''
ice_1   | |    295 | execute                          in     ''
ice_1   | |   3710 | invoke . . . . . . . . . . . . . in com.amazonaws.services.s3.AmazonS3Client
ice_1   | |   1146 | getObject                        in     ''
ice_1   | |   1018 | getObject . . . . . . . . . . .  in     ''
ice_1   | |    334 | download                         in com.netflix.ice.common.AwsUtils
ice_1   | |    329 | download . . . . . . . . . . . . in     ''
ice_1   | |    317 | downloadFileIfNotExist           in     ''
ice_1   | |    101 | init . . . . . . . . . . . . . . in com.netflix.ice.basic.BasicReservationService
ice_1   | |     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment . . . . .  in     ''
ice_1   | |    296 | executeForCurrentEnvironment     in     ''
ice_1   | |    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run                              in java.lang.Thread
ice_1   | | Error com.amazonaws.AmazonClientException: Unable to execute HTTP request:  -aws-billing-ice.s3.amazonaws.com
ice_1   | | Error 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:471)
ice_1   | | Error 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
ice_1   | | Error 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3710)
ice_1   | | Error 	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1146)
ice_1   | | Error 	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1018)
ice_1   | | Error 	at com.netflix.ice.common.AwsUtils.download(AwsUtils.java:334)
ice_1   | | Error 	at com.netflix.ice.common.AwsUtils.download(AwsUtils.java:329)
ice_1   | | Error 	at com.netflix.ice.common.AwsUtils.downloadFileIfNotExist(AwsUtils.java:317)
ice_1   | | Error 	at com.netflix.ice.basic.BasicReservationService.init(BasicReservationService.java:101)
ice_1   | | Error 	at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:95)
ice_1   | | Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
ice_1   | | Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
ice_1   | | Error 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
ice_1   | | Error 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
ice_1   | | Error 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
ice_1   | | Error 	at BootStrap$_closure1.doCall(BootStrap.groovy:186)
ice_1   | | Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ice_1   | | Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
ice_1   | | Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ice_1   | | Error 	at java.lang.reflect.Method.invoke(Method.java:606)
ice_1   | | Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
ice_1   | | Error 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
ice_1   | | Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
ice_1   | | Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1   | | Error 	at groovy.lang.Closure.call(Closure.java:423)
ice_1   | | Error 	at groovy.lang.Closure.call(Closure.java:417)
ice_1   | | Error 	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
ice_1   | | Error 	at grails.util.Environment.executeForEnvironment(Environment.java:320)
ice_1   | | Error 	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
ice_1   | | Error 	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
ice_1   | | Error 	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
ice_1   | | Error 	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
ice_1   | | Error 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
ice_1   | | Error 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
ice_1   | | Error 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
ice_1   | | Error 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
ice_1   | | Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
ice_1   | | Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
ice_1   | | Error 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
ice_1   | | Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
ice_1   | | Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
ice_1   | | Error 	at java.lang.Thread.run(Thread.java:745)
ice_1   | | Error Caused by: java.net.UnknownHostException:  -aws-billing-ice.s3.amazonaws.com
ice_1   | | Error 	at java.net.InetAddress.getAllByName0(InetAddress.java:1252)
ice_1   | | Error 	at java.net.InetAddress.getAllByName(InetAddress.java:1164)
ice_1   | | Error 	at java.net.InetAddress.getAllByName(InetAddress.java:1098)
ice_1   | | Error 	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
ice_1   | | Error 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:278)
ice_1   | | Error 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:162)
ice_1   | | Error 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
ice_1   | | Error 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:641)
ice_1   | | Error 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480)
ice_1   | | Error 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
ice_1   | | Error 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
ice_1   | | Error 	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:685)
ice_1   | | Error 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
ice_1   | | Error 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
ice_1   | | Error 	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3710)
ice_1   | | Error 	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1146)
ice_1   | | Error 	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1018)
ice_1   | | Error 	at com.netflix.ice.common.AwsUtils.download(AwsUtils.java:334)
ice_1   | | Error 	at com.netflix.ice.common.AwsUtils.download(AwsUtils.java:329)
ice_1   | | Error 	at com.netflix.ice.common.AwsUtils.downloadFileIfNotExist(AwsUtils.java:317)
ice_1   | | Error 	at com.netflix.ice.basic.BasicReservationService.init(BasicReservationService.java:101)
ice_1   | | Error 	at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:95)
ice_1   | | Error 	at BootStrap$_closure1.doCall(BootStrap.groovy:186)
ice_1   | | Error 	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
ice_1   | | Error 	at grails.util.Environment.executeForEnvironment(Environment.java:320)
ice_1   | | Error 	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
ice_1   | | Error 	... 4 more
ice_1   | | Error 2015-08-11 15:20:40,057 [localhost-startStop-1] ERROR BootStrap  - Startup failed
ice_1   | Message: Unable to execute HTTP request:  -aws-billing-ice.s3.amazonaws.com
ice_1   |     Line | Method
ice_1   | ->>  471 | executeHelper                    in com.amazonaws.http.AmazonHttpClient
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
ice_1   | |    295 | execute                          in     ''
ice_1   | |   3710 | invoke . . . . . . . . . . . . . in com.amazonaws.services.s3.AmazonS3Client
ice_1   | |   1146 | getObject                        in     ''
ice_1   | |   1018 | getObject . . . . . . . . . . .  in     ''
ice_1   | |    334 | download                         in com.netflix.ice.common.AwsUtils
ice_1   | |    329 | download . . . . . . . . . . . . in     ''
ice_1   | |    317 | downloadFileIfNotExist           in     ''
ice_1   | |    101 | init . . . . . . . . . . . . . . in com.netflix.ice.basic.BasicReservationService
ice_1   | |     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment . . . . .  in     ''
ice_1   | |    296 | executeForCurrentEnvironment     in     ''
ice_1   | |    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run                              in java.lang.Thread
ice_1   | 
ice_1   | Caused by UnknownHostException:  -aws-billing-ice.s3.amazonaws.com
ice_1   | ->> 1252 | getAllByName0                    in java.net.InetAddress
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
ice_1   | |   1164 | getAllByName                     in     ''
ice_1   | |   1098 | getAllByName . . . . . . . . . . in     ''
ice_1   | |     45 | resolve                          in org.apache.http.impl.conn.SystemDefaultDnsResolver
ice_1   | |    278 | resolveHostname . . . . . . . .  in org.apache.http.impl.conn.DefaultClientConnectionOperator
ice_1   | |    162 | openConnection                   in     ''
ice_1   | |    294 | open . . . . . . . . . . . . . . in org.apache.http.impl.conn.ManagedClientConnectionImpl
ice_1   | |    641 | tryConnect                       in org.apache.http.impl.client.DefaultRequestDirector
ice_1   | |    480 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    906 | execute                          in org.apache.http.impl.client.AbstractHttpClient
ice_1   | |    805 | execute . . . . . . . . . . . .  in     ''
ice_1   | |    685 | executeOneRequest                in com.amazonaws.http.AmazonHttpClient
ice_1   | |    460 | executeHelper . . . . . . . . .  in     ''
ice_1   | |    295 | execute                          in     ''
ice_1   | |   3710 | invoke . . . . . . . . . . . . . in com.amazonaws.services.s3.AmazonS3Client
ice_1   | |   1146 | getObject                        in     ''
ice_1   | |   1018 | getObject . . . . . . . . . . .  in     ''
ice_1   | |    334 | download                         in com.netflix.ice.common.AwsUtils
ice_1   | |    329 | download . . . . . . . . . . . . in     ''
ice_1   | |    317 | downloadFileIfNotExist           in     ''
ice_1   | |    101 | init . . . . . . . . . . . . . . in com.netflix.ice.basic.BasicReservationService
ice_1   | |     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment . . . . .  in     ''
ice_1   | |    296 | executeForCurrentEnvironment     in     ''
ice_1   | |    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run                              in java.lang.Thread
dockerice_ice_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
Stopping dockerice_nginx_1...

Do you know what's happend ?

My user can access to the s3 bucket using boto.

**Comment by jonbrouse** [comment]
Sorry for the delay... Could you post the ice/assets/ice.properties? Remember to remove your AWS keys.

**Comment by thinhduckhoi** [comment]
I got the same error and couldn't figure out how to fix it.
