### ISSUE TITLE
 BootStrap - NPE error after `Reading tag.properties`

### ISSUE THREAD

**Issue by david-dumas** [jonbrouse/docker-ice#38]
Using image `jonbrouse/ice:latest` from a month ago with the following `ice.properties`:
```
ice.processor=true
ice.reader=true
ice.reservationCapacityPoller=false
ice.reservationPeriod=threeyear
ice.reservationUtilization=MEDIUM
ice.highstockUrl=https://code.highcharts.com/stock/4.2.1/highstock.js
ice.urlPrefix=<hidden>
ice.fromEmail=<hidden>
ice.ondemandCostAlertThreshold=250
ice.ondemandCostAlertEmails=
ice.billing_s3bucketname=effilab-business
ice.billing_s3bucketregion=eu-west-1
ice.billing_s3bucketprefix=
ice.startmillis=1469916000000
ice.companyName=Effilab
ice.work_s3bucketname=effilab-ice
ice.work_s3bucketprefix=ice/
ice.processor.localDir=/mnt/ice_processor
ice.reader.localDir=/mnt/ice_reader
ice.monthlycachesize=12
ice.account.account1=<hidden>
ice.owneraccount.account1.role=ice
ice.owneraccount.account2.role=ice
ice.owneraccount.account5.role=ice
ice.owneraccount.account1.externalId=
ice.owneraccount.account2.externalId=
ice.owneraccount.account5.externalId=
```
I have a similar issue to #28 
```2018-08-06 17:01:31,199 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
2018-08-06 17:01:31,199 [localhost-startStop-1] INFO  BootStrap  - Read ice.properties ...
2018-08-06 17:01:31,208 [localhost-startStop-1] INFO  BootStrap  - Reading tag.properties...
| Error java.lang.NullPointerException
| Error 	at java.util.Hashtable.put(Hashtable.java:459)
| Error 	at java.util.Properties.setProperty(Properties.java:166)
| Error 	at java_util_Properties$setProperty$1.call(Unknown Source)
| Error 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
| Error 	at BootStrap$_closure1.doCall(BootStrap.groovy:117)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:498)
| Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
| Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
| Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
| Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error 	at groovy.lang.Closure.call(Closure.java:423)
| Error 	at groovy.lang.Closure.call(Closure.java:417)
| Error 	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
| Error 	at grails.util.Environment.executeForEnvironment(Environment.java:320)
| Error 	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
| Error 	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
| Error 	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
| Error 	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
| Error 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
| Error 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
| Error 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
| Error 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
| Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
| Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
| Error 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
| Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
| Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
| Error 	at java.lang.Thread.run(Thread.java:748)
| Error 2018-08-06 17:01:31,446 [localhost-startStop-1] ERROR BootStrap  - Startup failed
```
I can't find a way to debug this, my `ice.properties` didn't change, I just updated my IAM key/secret used in:
```
        args:
          - -Djava.net.preferIPv4Stack=true
          - -Djava.net.preferIPv4Addresses
          - -Duser.timezone=Europe/Paris
          - -Dice.s3AccessKeyId=<hidden>
          - -Dice.s3SecretKey=<hidden>
          - run-app
        env:
        - name: GRAILS_OPTS
          value: "-server -Xmx4g -Xms1g -Dfile.encoding=UTF-8"
```

**Comment by mmh** [comment]
We just hit an issue with the exact same Error after a redeploy of `jonbrouse/ice:latest` without any changes to the configuration.

**Comment by david-dumas** [comment]
I solved this temporary by rebuilding the docker image with a Debian 8 base, IMO Alpine is too unstable:
```
FROM java:8-jdk

RUN export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get upgrade -y \
 && apt-get install -y --no-install-recommends bash curl unzip tree tar sed \
 && apt-get autoremove -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```
But then I have java 8u111, it's a little late.

**Comment by mmh** [comment]
Thanks @david-dumas 
Based on that input I rebuild the container with just `openjdk:alpine` instead of `openjdk:8u131-jdk-alpine` to get a newer jdk version where the app can now start.

**Comment by jonbrouse** [comment]
[Updated source image](https://github.com/jonbrouse/docker-ice/commit/d1f2403e04573ad3769fed32a0c796e0357cd05d)
