### ISSUE TITLE
Issues starting up.

### ISSUE THREAD

**Issue by fitchtravis** [jonbrouse/docker-ice#41]
I'm using Jim Roths forked version of this ...

when doing `docker-compose up` I get following error.

In the ice.properties, what should `ice.reader.localDir` and `ice.processor.localDir` be set to?

`ice_1    | | Error java.lang.ArrayIndexOutOfBoundsException: 0
ice_1    | | Error      at com.netflix.ice.processor.ProcessorConfig.processBillingDataConfig(ProcessorConfig.java:394)
ice_1    | | Error      at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:148)
ice_1    | | Error      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
ice_1    | | Error      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
ice_1    | | Error      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
ice_1    | | Error      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
ice_1    | | Error      at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
ice_1    | | Error      at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
ice_1    | | Error      at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
ice_1    | | Error      at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
ice_1    | | Error      at BootStrap$_closure1.doCall(BootStrap.groovy:183)
ice_1    | | Error      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ice_1    | | Error      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ice_1    | | Error      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ice_1    | | Error      at java.lang.reflect.Method.invoke(Method.java:498)
ice_1    | | Error      at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
ice_1    | | Error      at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
ice_1    | | Error      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
ice_1    | | Error      at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1    | | Error      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1    | | Error      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
ice_1    | | Error      at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1    | | Error      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1    | | Error      at groovy.lang.Closure.call(Closure.java:423)
ice_1    | | Error      at groovy.lang.Closure.call(Closure.java:417)
ice_1    | | Error      at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
ice_1    | | Error      at grails.util.Environment.executeForEnvironment(Environment.java:320)
ice_1    | | Error      at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
ice_1    | | Error      at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
ice_1    | | Error      at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
ice_1    | | Error      at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
ice_1    | | Error      at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
ice_1    | | Error      at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
ice_1    | | Error      at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
ice_1    | | Error      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
ice_1    | | Error      at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
ice_1    | | Error      at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
ice_1    | | Error      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ice_1    | | Error      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ice_1    | | Error      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ice_1    | | Error      at java.lang.Thread.run(Thread.java:748)
ice_1    | | Error 2019-07-04 00:02:51,173 [localhost-startStop-1] ERROR BootStrap  - Startup failed
ice_1    | Message: 0
ice_1    |     Line | Method
ice_1    | ->>  394 | processBillingDataConfig         in com.netflix.ice.processor.ProcessorConfig
ice_1    | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ice_1    | |    148 | <init>                           in     ''
ice_1    | |    183 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1    | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1    | |    320 | executeForEnvironment . . . . .  in     ''
ice_1    | |    296 | executeForCurrentEnvironment     in     ''
ice_1    | |    266 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1    | |   1149 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1    | |    624 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1    | ^    748 | run                              in java.lang.Thread
ice-docker_ice_1 exited with code 0`

**Comment by agent462** [comment]
This is likely something else in your configuration.  Share your ice.properties.
