### ISSUE TITLE
ERROR BootStrap  - Startup failed

### ISSUE THREAD

**Issue by bloo0** [jonbrouse/docker-ice#50]
**I'm having errors below, not sure what to find:**

ice_1    | | Error java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
ice_1    | | Error      at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
ice_1    | | Error      at java.util.LinkedList.get(LinkedList.java:476)
ice_1    | | Error      at com.netflix.ice.processor.ProcessorConfig.readBillingDataConfig(ProcessorConfig.java:565)
ice_1    | | Error      at com.netflix.ice.processor.ProcessorConfig.processBillingDataConfig(ProcessorConfig.java:512)
ice_1    | | Error      at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:143)
ice_1    | | Error      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
ice_1    | | Error      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
ice_1    | | Error      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
ice_1    | | Error      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
ice_1    | | Error      at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
ice_1    | | Error      at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
ice_1    | | Error      at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
ice_1    | | Error      at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
ice_1    | | Error      at BootStrap$_closure1.doCall(BootStrap.groovy:190)
ice_1    | | Error      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ice_1    | | Error      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ice_1    | | Error      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ice_1    | | Error      at java.lang.reflect.Method.invoke(Method.java:498)
ice_1    | | Error      at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
ice_1    | | Error      at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
ice_1    | | Error      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
ice_1    | | Error      at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1    | | Error      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1    | | Error      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
ice_1    | | Error      at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1    | | Error      at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1    | | Error      at groovy.lang.Closure.call(Closure.java:423)
ice_1    | | Error      at groovy.lang.Closure.call(Closure.java:417)
ice_1    | | Error      at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
ice_1    | | Error      at grails.util.Environment.executeForEnvironment(Environment.java:320)
ice_1    | | Error      at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
ice_1    | | Error      at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
ice_1    | | Error      at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
ice_1    | | Error      at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
ice_1    | | Error      at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
ice_1    | | Error      at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
ice_1    | | Error      at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
ice_1    | | Error      at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
ice_1    | | Error      at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
ice_1    | | Error      at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
ice_1    | | Error      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ice_1    | | Error      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ice_1    | | Error      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ice_1    | | Error      at java.lang.Thread.run(Thread.java:748)
ice_1    | | Error 2020-07-19 20:11:32,576 [localhost-startStop-1] ERROR BootStrap  - Startup failed
ice_1    | Message: Index: 0, Size: 0
ice_1    |     Line | Method
ice_1    | ->>  555 | checkElementIndex                in java.util.LinkedList
ice_1    | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ice_1    | |    476 | get                              in     ''
ice_1    | |    565 | readBillingDataConfig . . . . .  in com.netflix.ice.processor.ProcessorConfig
ice_1    | |    512 | processBillingDataConfig         in     ''
ice_1    | |    143 | <init> . . . . . . . . . . . . . in     ''
ice_1    | |    190 | doCall                           in BootStrap$_closure1
ice_1    | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1    | |    320 | executeForEnvironment            in     ''
ice_1    | |    296 | executeForCurrentEnvironment . . in     ''
ice_1    | |    266 | run                              in java.util.concurrent.FutureTask
ice_1    | |   1149 | runWorker . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
ice_1    | |    624 | run                              in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1    | ^    748 | run . . . . . . . . . . . . . .  in java.lang.Thread

**Comment by slumbang129** [comment]
I am also experiencing the same issue.  Not sure if this is the culprit 

ice_1    | 2020-12-08 04:20:19,216 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStatic] to [false] as the property does not exist.
ice_1    | 2020-12-08 04:20:19,219 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopThreads] to [false] as the property does not exist.
ice_1    | 2020-12-08 04:20:19,219 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopTimerThreads] to [false] as the property does not exist.
ice_1    | 2020-12-08 04:20:19,220 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesHttpClientKeepAliveThread] to [true] as the property does not exist.
ice_1    | 2020-12-08 04:20:19,234 [localhost-startStop-1] INFO  startup.ContextConfig  - No global web.xml found
ice_1    | 2020-12-08 04:20:19,445 [localhost-startStop-1] INFO  [localhost].[/ice]  - No Spring WebApplicationInitializer types detected on classpath
ice_1    | 2020-12-08 04:20:19,503 [localhost-startStop-1] INFO  [localhost].[/ice]  - Initializing Spring root WebApplicationContext
ice_1    | 2020-12-08 04:20:29,154 [localhost-startStop-1] INFO  context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
ice_1    | 2020-12-08 04:20:29,224 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
ice_1    | 2020-12-08 04:20:29,225 [localhost-startStop-1] INFO  BootStrap  - Read ice.properties ...
ice_1    | 2020-12-08 04:20:46,444 [localhost-startStop-1] INFO  processor.ProcessorConfig  - Get account/organizational unit hierarchy for 641885301384 using assume role "", and external id ""
ice_1    | 2020-12-08 04:20:49,418 [localhost-startStop-1] INFO  processor.ProcessorConfig  - Get accounts for organization  using assume role "", and external id ""
ice_1    | 2020-12-08 04:20:54,552 [localhost-startStop-1] INFO  processor.ProcessorConfig  - Look for data config: accurics-monthly-report, us-east-2, MonthlyCostUsageReport/ice_config, 
ice_1    | | Error java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

**Comment by nfonrose** [comment]
Hello,

Hard to tell based on what you are sharing.
Do you have more error logs? Can you share more of how you start Ice? On an
AWS machine with an IAM role, on a local developer machine?

Nicolas

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
https://teevity.com - Cloud Costs Analytics for AWS, GCP and Azure powered
by NetflixOSS Ice
twitter - @nfonrose / @teevity

**Comment by slumbang129** [comment]
hi @nfonrose 

I am using local running docker compose up.  I'm not using IAM role, Just using main account with access to the bucket.

I removed the account number on the logs..the only thing i didnt declare is role id or external id which i feel it doesn't need?

sherwinlumbang$ docker-compose up
Creating network "docker-ice_default" with the default driver
Creating docker-ice_ice_1 ... done
Creating docker-ice_nginx_1 ... done
Attaching to docker-ice_ice_1, docker-ice_nginx_1
ice_1    | | Loading Grails 2.4.4
ice_1    | | Configuring classpath
ice_1    | Dec 09, 2020 4:47:59 PM java.util.prefs.FileSystemPreferences$1 run
ice_1    | INFO: Created user preferences directory.
ice_1    | | Configuring classpath.
ice_1    | | Environment set to development
ice_1    | | Environment set to development.
ice_1    | | Environment set to development..
ice_1    | | Environment set to development...
ice_1    | | Environment set to development....
ice_1    | | Environment set to development.....
ice_1    | | Packaging Grails application
ice_1    | | Installing zip tomcat-8.0.20.zip...
ice_1    | | Installing zip tomcat-8.0.20.zip....
ice_1    | | Installing zip tomcat-8.0.20.zip.....
ice_1    | | Installed plugin tomcat-8.0.20
ice_1    | | Installed plugin tomcat-8.0.20.
ice_1    | | Installed plugin tomcat-8.0.20..
ice_1    | | Installed plugin tomcat-8.0.20...
ice_1    | | Installed plugin tomcat-8.0.20....
ice_1    | | Installed plugin tomcat-8.0.20.....
ice_1    | | Compiling 10 source files
ice_1    | 
ice_1    | | Compiling 10 source files.
ice_1    | | Compiling 10 source files..
ice_1    | | Compiling 10 source files
ice_1    | 
ice_1    | | Compiling 10 source files.
ice_1    | | Compiling 10 source files..
ice_1    | | Compiling 10 source files...
ice_1    | | Compiling 10 source files....
ice_1    | | Compiling 10 source files.....
ice_1    | | Compiling 133 source files
ice_1    | 
ice_1    | | Compiling 133 source files.
ice_1    | | Compiling 133 source files..
ice_1    | | Compiling 133 source files...
ice_1    | | Compiling 133 source files....
ice_1    | | Compiling 133 source files.....
ice_1    | | Running Grails application
ice_1    | 2020-12-09 16:48:22,102 [main] INFO  http11.Http11NioProtocol  - Initializing ProtocolHandler ["http-nio-8080"]
ice_1    | 2020-12-09 16:48:22,153 [main] INFO  net.NioSelectorPool  - Using a shared selector for servlet write/read
ice_1    | 2020-12-09 16:48:22,186 [main] INFO  core.StandardService  - Starting service Tomcat
ice_1    | 2020-12-09 16:48:22,187 [main] INFO  core.StandardEngine  - Starting Servlet Engine: Apache Tomcat/8.0.20
ice_1    | 2020-12-09 16:48:22,352 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStatic] to [false] as the property does not exist.
ice_1    | 2020-12-09 16:48:22,354 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopThreads] to [false] as the property does not exist.
ice_1    | 2020-12-09 16:48:22,355 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopTimerThreads] to [false] as the property does not exist.
ice_1    | 2020-12-09 16:48:22,355 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesHttpClientKeepAliveThread] to [true] as the property does not exist.
ice_1    | 2020-12-09 16:48:22,367 [localhost-startStop-1] INFO  startup.ContextConfig  - No global web.xml found
ice_1    | 2020-12-09 16:48:22,584 [localhost-startStop-1] INFO  [localhost].[/ice]  - No Spring WebApplicationInitializer types detected on classpath
ice_1    | 2020-12-09 16:48:22,639 [localhost-startStop-1] INFO  [localhost].[/ice]  - Initializing Spring root WebApplicationContext
ice_1    | 2020-12-09 16:48:30,630 [localhost-startStop-1] INFO  context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
ice_1    | 2020-12-09 16:48:30,695 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
ice_1    | 2020-12-09 16:48:30,695 [localhost-startStop-1] INFO  BootStrap  - Read ice.properties ...
ice_1    | 2020-12-09 16:48:46,640 [localhost-startStop-1] INFO  processor.ProcessorConfig  - Get account/organizational unit hierarchy for <AWS ID> using assume role "", and external id ""
ice_1    | 2020-12-09 16:48:49,838 [localhost-startStop-1] INFO  processor.ProcessorConfig  - Get accounts for organization <AWS ID> using assume role "", and external id ""
ice_1    | 2020-12-09 16:48:55,128 [localhost-startStop-1] INFO  processor.ProcessorConfig  - Look for data config: accurics-monthly-report, us-east-2, accurics/MonthlyCostUsageReport/ice_config, <AWS ID>
ice_1    | | Error java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
