### ISSUE TITLE
Trouble during launch docker-compose - basic.BasicReservationService

### ISSUE THREAD

**Issue by JulienChampseix** [jonbrouse/docker-ice#7]
Hi Team,

When i run "docker-compose up" using an AWS IAM access having full access i'm getting this error : 

```
ice_1   | 2016-02-25 10:20:20,900 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
ice_1   | 2016-02-25 10:20:25,374 [localhost-startStop-1] INFO  common.AwsUtils  - file not found in s3 /mnt/ice_processor/reservation_prices.threeyear.LIGHT
ice_1   | 2016-02-25 10:20:25,875 [localhost-startStop-1] INFO  common.AwsUtils  - file not found in s3 /mnt/ice_processor/reservation_prices.threeyear.MEDIUM
ice_1   | 2016-02-25 10:20:26,111 [localhost-startStop-1] INFO  common.AwsUtils  - file not found in s3 /mnt/ice_processor/reservation_prices.threeyear.HEAVY
ice_1   | 2016-02-25 10:20:26,649 [localhost-startStop-1] INFO  common.AwsUtils  - file not found in s3 /mnt/ice_processor/reservation_prices.threeyear.FIXED
ice_1   | | Error 2016-02-25 10:20:30,712 [localhost-startStop-1] ERROR basic.BasicReservationService  - No Zone for ap-southeast-2c
ice_1   | | Error 2016-02-25 10:20:30,726 [localhost-startStop-1] ERROR basic.BasicReservationService  - failed to poll reservation prices
ice_1   | Message: null
ice_1   |     Line | Method
ice_1   | ->>  177 | pollAPI                          in com.netflix.ice.basic.BasicReservationService
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ice_1   | |    106 | init                             in     ''
ice_1   | |     95 | <init> . . . . . . . . . . . . . in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall                           in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment            in     ''
ice_1   | |    296 | executeForCurrentEnvironment . . in     ''
ice_1   | |    262 | run                              in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run                              in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run . . . . . . . . . . . . . .  in java.lang.Thread
ice_1   | | Error java.lang.RuntimeException: failed to poll reservation prices for null
ice_1   | | Error 	at com.netflix.ice.basic.BasicReservationService.init(BasicReservationService.java:110)
ice_1   | | Error 	at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:95)
ice_1   | | Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
ice_1   | | Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
ice_1   | | Error 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
ice_1   | | Error 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
ice_1   | | Error 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
ice_1   | | Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
ice_1   | | Error 	at BootStrap$_closure1.doCall(BootStrap.groovy:186)
ice_1   | | Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ice_1   | | Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
ice_1   | | Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ice_1   | | Error 	at java.lang.reflect.Method.invoke(Method.java:606)
ice_1   | | Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
ice_1   | | Error 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
ice_1   | | Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
ice_1   | | Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
ice_1   | | Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
ice_1   | | Error 	at groovy.lang.Closure.call(Closure.java:423)
ice_1   | | Error 	at groovy.lang.Closure.call(Closure.java:417)
ice:
ice_1   | | Error 	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
ice_1   | | Error 	at grails.util.Environment.executeForEnvironment(Environment.java:320)
ice_1   | | Error 	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
ice_1   | | Error 	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
ice_1   | | Error 	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
ice_1   | | Error 	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
ice_1   | | Error 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
ice_1   | | Error 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
ice_1   | | Error 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
ice_1   | | Error 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
ice_1   | | Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
ice_1   | | Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
ice:
ice_1   | | Error 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
ice_1   | | Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
ice_1   | | Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
ice_1   | | Error 	at java.lang.Thread.run(Thread.java:745)
ice_1   | | Error 2016-02-25 10:20:30,793 [localhost-startStop-1] ERROR BootStrap  - Startup failed
ice_1   | Message: failed to poll reservation prices for null
ice_1   |     Line | Method
ice_1   | ->>  110 | init                             in com.netflix.ice.basic.BasicReservationService
ice_1   | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
ice_1   | |     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
ice_1   | |    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
ice_1   | |    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
ice_1   | |    320 | executeForEnvironment . . . . .  in     ''
ice_1   | |    296 | executeForCurrentEnvironment     in     ''
ice_1   | |    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
ice_1   | |   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
ice_1   | |    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
ice_1   | ^    745 | run                              in java.lang.Thread
```

Find bellow my config bellow : 

ice.processor=true
ice.reader=true
ice.reservationCapacityPoller=false
ice.reservationPeriod=threeyear
ice.reservationUtilization=MEDIUM
ice.highstockUrl=http://code.highcharts.com/stock/highstock.js
ice.urlPrefix=
ice.fromEmail=
ice.ondemandCostAlertThreshold=250
ice.ondemandCostAlertEmails=
ice.billing_s3bucketname=billing-aws
ice.billing_s3bucketprefix=,
ice.startmillis=1364774400000
ice.companyName=Test
ice.work_s3bucketname=test-billing
ice.work_s3bucketprefix=ice/
ice.processor.localDir=/mnt/ice_processor
ice.reader.localDir=/mnt/ice_reader
ice.monthlycachesize=12
ice.owneraccount.account1.role=ice
ice.owneraccount.account2.role=ice
ice.owneraccount.account5.role=ice
ice.owneraccount.account1.externalId=
ice.owneraccount.account2.externalId=
ice.owneraccount.account5.externalId=

Is it due the image from image: jonbrouse/ice:latest is too old meaning dont have all fix from Netflix/ice repo about Reservation ?

**Comment by nfonrose** [comment]
Hello Julien,

This is strange since the Netflix Ice team has just merged the PR that
fixes this problem inside the Ice repo.
Are your sure that the docker composition is pulling the latest Ice release
?

Nicolas

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
http://www.teevity.com - Cloud Costs Analytics powered by NetflixOSS
twitter - @nfonrose / @teevity



On Thu, Feb 25, 2016 at 11:36 AM, Julien CHAMPSEIX <notifications@github.com

**Comment by JulienChampseix** [comment]
Find bellow my docker-compose.yml:
ice:
  image: jonbrouse/ice:latest
  command: |
    -Djava.net.preferIPv4Stack=true
    -Djava.net.preferIPv4Addresses
    -Dice.s3AccessKeyId=XXXXXX
    -Dice.s3SecretKey=XXXXXXX
    run-app
  volumes:
    - ./ice/assets/ice.properties:/opt/ice/src/java/ice.properties
nginx:
  image: jonbrouse/ice-proxy:latest
  ports:
    - "80:80"
  links:
    - ice:ice

**Comment by nfonrose** [comment]
On Thu, Feb 25, 2016 at 3:25 PM, Julien CHAMPSEIX <notifications@github.com>
wrote:

> jonbrouse/ice:latest


That's probably the issue. If this docker image hasn't been updated to the
latest Ice commit (from a few days ago), then your missing the simple fix
that adds the new zone (ap-southeast-2c).

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
http://www.teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by JulienChampseix** [comment]
@jonbrouse can you update the docker image ?

**Comment by jonbrouse** [comment]
Hey, I just kicked off a new build a created a 2.0 tag as well.

**Comment by JulienChampseix** [comment]
Perfect, that fixed the issue ! Thanks @jonbrouse

**Comment by JulienChampseix** [comment]
@jonbrouse An other issue running _docker-compose up_ appear using your latest build : 

ice_1   | | Error 2016-02-26 15:20:04,698 [localhost-startStop-1] ERROR basic.BasicReservationService  - failed to poll reservation prices
ice_1   | Message: /mnt/ice_processor/reservation_prices.threeyear.MEDIUM (No such file or directory)

The exist /mnt/ice_processor/ but nothing inside.

**Comment by nfonrose** [comment]
Hey Julien,

This is not related to [docker-ice] but to Ice itself. Wrong repo for the
question :-)

Nicolas

--
Nicolas Fonrose | Teevity | Founder
+33.6.61.35.43.31
http://www.teevity.com - Cloud Costs Analytics built on NetflixOSS
twitter - @nfonrose / @teevity

**Comment by jonbrouse** [comment]
Thank you for the guidance @nfonrose 

@JulienChampseix I'm going to close this issue.
